name: Main.js CI

on:
  push:
    branches: [front-test, final-1]
  pull_request:
    branches: [front-test]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # just comment
    # - run: npm i
    # - name: 'Create env file'
    #   run: ||
    #       npm run build
    # tmcmm allal
